### ISSUE TITLE
KeyError: 'cancelled duplicate' when getting an completed operation.

### ISSUE THREAD

**Issue by samuelarjasbi** [Plisio/plisio-python#6]
I payed an invoice in order to complete a operation to test my code, when I use `client.get_operation("663a72b05597c15a0f02bcb3")` it returns this error 

```
Traceback (most recent call last):
  File "F:\Projects\API\test.py", line 9, in <module>
    data = client.get_operation("663a72b05597c15a0f02bcb3")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Projects\API\env\Lib\site-packages\plisio\plisio_client.py", line 435, in get_operation
    return self._send_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Projects\API\env\Lib\site-packages\plisio\plisio_client.py", line 261, in _send_request
    request.set_response(status, data)
  File "F:\Projects\API\env\Lib\site-packages\plisio\plisio_client.py", line 42, in set_response
    self.__handle_processed_request(response_dict)
  File "F:\Projects\API\env\Lib\site-packages\plisio\plisio_client.py", line 51, in __handle_processed_request
    self.__response = self.__response_class.from_response(data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Projects\API\env\Lib\site-packages\plisio\plisio_models.py", line 559, in from_response
    response_dict.get('status') and plisio.OperationStatus[response_dict['status']],
                                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Projects\API\env\Lib\site-packages\plisio\plisio_enums.py", line 8, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 797, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'cancelled duplicate'
```

**Comment by AlexAlexDudko** [comment]
Hi! Resolved in Resolved in plisio 1.0.10 https://pypi.org/project/plisio/1.0.10/
